ignore:
  - "api.mapserv.utah.gov/Exceptions"
  - "api.mapserv.utah.gov/Formatters"
  - "api.mapserv.utah.gov/Program.cs"
  - "api.mapserv.utah.gov/Startup.cs"
  - "api.mapserv.utah.gov/Extensions/ServiceCollectionExtensions.cs"
  - "api.mapserv.utah.gov/Extensions/MvcOptionsExtensions.cs"
  - "api.mapserv.utah.gov/Services/PostmanApiKeyRepository.cs"
  - "api.mapserv.utah.gov/Services/PostgreApiKeyRepository.cs"
