ignore:
  - "src/api/Exceptions"
  - "src/api/Formatters"
  - "src/api/Program.cs"
  - "src/api/Startup.cs"
  - "src/api/Extensions/ServiceCollectionExtensions.cs"
  - "src/api/Extensions/MvcOptionsExtensions.cs"
  - "src/api/Services/PostmanApiKeyRepository.cs"
  - "src/api/Services/PostgreApiKeyRepository.cs"
