apiVersion: v1
data:
  appsettings.json: "\uFEFF\x7B\n\x20\x20\"\x53\x65\x72\x69\x6C\x6F\x67\"\x3A\x20\x7B\n\x20\x20\"\x55\x73\x69\x6E\x67\"\x3A\x20\x5B\n\x20\x20\x20\x20\"\x53\x65\x72\x69\x6C\x6F\x67\x2E\x53\x69\x6E\x6B\x73\x2E\x43\x6F\x6E\x73\x6F\x6C\x65\"\n\x20\x20\x5D\x2C\n\x20\x20\"\x4D\x69\x6E\x69\x6D\x75\x6D\x4C\x65\x76\x65\x6C\"\x3A\x20\x7B\n\x20\x20\x20\x20\"\x44\x65\x66\x61\x75\x6C\x74\"\x3A\x20\"\x49\x6E\x66\x6F\x72\x6D\x61\x74\x69\x6F\x6E\"\x2C\n\x20\x20\x20\x20\"\x4F\x76\x65\x72\x72\x69\x64\x65\"\x3A\x20\x7B\n\x20\x20\x20\x20\x20\x20\"\x4D\x69\x63\x72\x6F\x73\x6F\x66\x74\"\x3A\x20\"\x57\x61\x72\x6E\x69\x6E\x67\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x4D\x69\x63\x72\x6F\x73\x6F\x66\x74\x2E\x48\x6F\x73\x74\x69\x6E\x67\x2E\x4C\x69\x66\x65\x74\x69\x6D\x65\"\x3A\x20\"\x49\x6E\x66\x6F\x72\x6D\x61\x74\x69\x6F\x6E\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x43\x6F\x72\x72\x65\x6C\x61\x74\x69\x6F\x6E\x49\x64\"\x3A\x20\"\x57\x61\x72\x6E\x69\x6E\x67\"\n\x20\x20\x20\x20\x7D\n\x20\x20\x7D\x2C\n\x20\x20\"\x57\x72\x69\x74\x65\x54\x6F\"\x3A\x20\x5B\"\x43\x6F\x6E\x73\x6F\x6C\x65\"\x5D\x2C\n\x20\x20\"\x45\x6E\x72\x69\x63\x68\"\x3A\x20\x5B\n\x20\x20\x20\x20\"\x46\x72\x6F\x6D\x4C\x6F\x67\x43\x6F\x6E\x74\x65\x78\x74\"\n\x20\x20\x20\x20\x5D\n\x20\x20\x7D\x2C\n\x20\x20\"\x41\x6C\x6C\x6F\x77\x65\x64\x48\x6F\x73\x74\x73\"\x3A\x20\"\x2A\"\x2C\n\x20\x20\"\x77\x65\x62\x61\x70\x69\"\x3A\x20\x7B\n\x20\x20\x20\x20\"\x61\x72\x63\x67\x69\x73\"\x3A\x20\x7B\n\x20\x20\x20\x20\x20\x20\"\x68\x6F\x73\x74\"\x3A\x20\"\x67\x65\x6F\x63\x6F\x64\x69\x6E\x67\x2D\x68\x6F\x73\x74\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x70\x6F\x72\x74\"\x3A\x20\x38\x30\x2C\n\x20\x20\x20\x20\x20\x20\"\x67\x65\x6F\x6D\x65\x74\x72\x79\x53\x65\x72\x76\x69\x63\x65\"\x3A\x20\x7B\n\x20\x20\x20\x20\x20\x20\x20\x20\"\x70\x61\x74\x68\"\x3A\x20\"\x61\x72\x63\x67\x69\x73\x2F\x72\x65\x73\x74\x2F\x73\x65\x72\x76\x69\x63\x65\x73\x2F\x47\x65\x6F\x6D\x65\x74\x72\x79\x2F\x47\x65\x6F\x6D\x65\x74\x72\x79\x53\x65\x72\x76\x65\x72\"\n\x20\x20\x20\x20\x20\x20\x7D\n\x20\x20\x20\x20\x7D\x2C\n\x20\x20\x20\x20\"\x6C\x6F\x63\x61\x74\x6F\x72\x73\"\x3A\x20\x5B\x7B\n\x20\x20\x20\x20\x20\x20\"\x68\x6F\x73\x74\"\x3A\x20\"\x67\x65\x6F\x63\x6F\x64\x69\x6E\x67\x2D\x68\x6F\x73\x74\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x64\x69\x73\x70\x6C\x61\x79\x4E\x61\x6D\x65\"\x3A\x20\"\x43\x65\x6E\x74\x65\x72\x6C\x69\x6E\x65\x73\x2E\x53\x74\x61\x74\x65\x77\x69\x64\x65\x52\x6F\x61\x64\x73\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x73\x65\x72\x76\x69\x63\x65\x4E\x61\x6D\x65\"\x3A\x20\"\x52\x6F\x61\x64\x73\x5F\x41\x64\x64\x72\x65\x73\x73\x53\x79\x73\x74\x65\x6D\x5F\x53\x54\x52\x45\x45\x54\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x72\x65\x76\x65\x72\x73\x65\x47\x65\x6F\x63\x6F\x64\x65\x73\"\x3A\x20\x74\x72\x75\x65\x2C\n\x20\x20\x20\x20\x20\x20\"\x6C\x6F\x63\x61\x74\x6F\x72\x54\x79\x70\x65\"\x3A\x20\"\x52\x6F\x61\x64\x43\x65\x6E\x74\x65\x72\x6C\x69\x6E\x65\x73\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x77\x65\x69\x67\x68\x74\"\x3A\x20\x30\x2C\n\x20\x20\x20\x20\x20\x20\"\x70\x61\x74\x68\x54\x6F\x4C\x6F\x63\x61\x74\x6F\x72\"\x3A\x20\"\x2F\x61\x72\x63\x67\x69\x73\x2F\x72\x65\x73\x74\x2F\x73\x65\x72\x76\x69\x63\x65\x73\x2F\x47\x65\x6F\x6C\x6F\x63\x61\x74\x6F\x72\x73\x2F\"\n\x20\x20\x20\x20\x7D\x2C\x20\x7B\n\x20\x20\x20\x20\x20\x20\"\x68\x6F\x73\x74\"\x3A\x20\"\x67\x65\x6F\x63\x6F\x64\x69\x6E\x67\x2D\x68\x6F\x73\x74\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x64\x69\x73\x70\x6C\x61\x79\x4E\x61\x6D\x65\"\x3A\x20\"\x41\x64\x64\x72\x65\x73\x73\x50\x6F\x69\x6E\x74\x73\x2E\x41\x64\x64\x72\x65\x73\x73\x47\x72\x69\x64\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x73\x65\x72\x76\x69\x63\x65\x4E\x61\x6D\x65\"\x3A\x20\"\x41\x64\x64\x72\x65\x73\x73\x50\x6F\x69\x6E\x74\x73\x5F\x41\x64\x64\x72\x65\x73\x73\x53\x79\x73\x74\x65\x6D\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x72\x65\x76\x65\x72\x73\x65\x47\x65\x6F\x63\x6F\x64\x65\x73\"\x3A\x20\x66\x61\x6C\x73\x65\x2C\n\x20\x20\x20\x20\x20\x20\"\x6C\x6F\x63\x61\x74\x6F\x72\x54\x79\x70\x65\"\x3A\x20\"\x41\x64\x64\x72\x65\x73\x73\x50\x6F\x69\x6E\x74\x73\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x77\x65\x69\x67\x68\x74\"\x3A\x20\x31\x2C\n\x20\x20\x20\x20\x20\x20\"\x70\x61\x74\x68\x54\x6F\x4C\x6F\x63\x61\x74\x6F\x72\"\x3A\x20\"\x2F\x61\x72\x63\x67\x69\x73\x2F\x72\x65\x73\x74\x2F\x73\x65\x72\x76\x69\x63\x65\x73\x2F\x47\x65\x6F\x6C\x6F\x63\x61\x74\x6F\x72\x73\x2F\"\n\x20\x20\x20\x20\x7D\x5D\x2C\n\x20\x20\x20\x20\"\x64\x61\x74\x61\x62\x61\x73\x65\"\x3A\x20\x7B\n\x20\x20\x20\x20\x20\x20\"\x68\x6F\x73\x74\"\x3A\x20\"\x64\x62\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x70\x6F\x72\x74\"\x3A\x20\"\x35\x34\x33\x32\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x64\x62\"\x3A\x20\"\x77\x65\x62\x61\x70\x69\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x75\x73\x65\x72\x6E\x61\x6D\x65\"\x3A\x20\"\x70\x6F\x73\x74\x67\x72\x65\x73\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x70\x61\x73\x73\x77\x6F\x72\x64\"\x3A\x20\"\x77\x68\x61\x74\x20\x70\x61\x73\x73\x77\x6F\x72\x64\"\x2C\n\x20\x20\x20\x20\x20\x20\"\x70\x65\x70\x70\x65\x72\"\x3A\x20\"\x73\x70\x69\x63\x79\"\n\x20\x20\x20\x20\x7D\n\x20\x20\x7D\n\x7D\n"
kind: ConfigMap
metadata:
  name: api-app-settings-g9cmc6h2mk
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    tier: backend
  name: db
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: geocoding-host
spec:
  externalName: mapserv.utah.gov
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: api
    tier: backend
    version: 1.0.0
  name: webapi-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1337
  selector:
    app: api
    tier: backend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  name: data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: postgres
      tier: backend
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
        version: 1.0.0
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: webapi
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: what password
        image: gcr.io/ut-dts-agrc-web-api-dev/api.mapserv.utah.gov/db
        imagePullPolicy: Always
        name: db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
          subPath: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      tier: backend
  template:
    metadata:
      labels:
        app: api
        tier: backend
        version: 1.0.0
    spec:
      containers:
      - env:
        - name: ASPNETCORE_URLS
          value: http://+:1337
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        image: gcr.io/ut-dts-agrc-web-api-dev/api.mapserv.utah.gov/api
        livenessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 30
          periodSeconds: 15
        name: webapi-api
        ports:
        - containerPort: 1337
        readinessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            memory: 1536Mi
          requests:
            memory: 512Mi
        volumeMounts:
        - mountPath: /app/appsettings.json
          name: appsettings-config
          subPath: appsettings.json
      volumes:
      - configMap:
          name: app-config
        name: appsettings-config
---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: agrc-api-managed-cert
spec:
  domains:
  - agrc-api.dev.utah.gov
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: web-api-cluster-ingress
    networking.gke.io/managed-certificates: agrc-api-managed-cert
  name: webapi-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: webapi-api
          servicePort: http
        path: /*
