language: csharp
sudo: false
solution: api.mapserv.utah.gov.sln
mono: none
dotnet: 2.2.100-preview2-009404
script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=info /p:CoverletOutput=coverage.info /p:Configuration=Release api.mapserv.utah.gov.sln
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change
    on_failure: change
