version: '3'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapi/api

  developer:
    build:
      context: .
      dockerfile: src/developer/Dockerfile
    image: webapi/developer

  db:
    build:
      context: .
      dockerfile: data/pg/Dockerfile
    image: webapi/db

  explorer:
    build:
      context: ./src/explorer
      dockerfile: Dockerfile

  cache:
    image: redis:latest
