version: '3'

services:

  api:
    ports:
      - "1337:1337"
    environment:
      - ASPNETCORE_URLS=http://+:1337
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - cache

  developer:
    ports:
      - "1338:1338"
    environment:
      - ASPNETCORE_URLS=http://+:1338
      - ASPNETCORE_ENVIRONMENT=Development

  explorer:
    ports:
      - '8080:80'

  smocker:
    image: thiht/smocker
    ports:
      - 6443:8080
      - 8081:8081
