version: '3.4'

services:
  webapi-core:
    links:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1337:1337"
  postgres:
    environment:
      - POSTGRES_DB=webapi
      - POSTGRES_USER=postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  data: ./pgdata
