version: '3'

services:

  api:
    build:
      context: .
      dockerfile: api.mapserv.utah.gov/Dockerfile
    image: webapi/api

  developer:
    build:
      context: .
      dockerfile: developer.mapserv.utah.gov/Dockerfile
    image: webapi/developer

  db:
    build:
      context: .
      dockerfile: pgdata/Dockerfile
    image: webapi/db

  cache:
    image: redis:latest
