services:

  api:
    ports:
      - "1337:1337"
    environment:
      - ASPNETCORE_URLS=http://+:1337
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - cache

  cache:
    ports:
      - 6379:6379

  smocker:
    image: thiht/smocker
    ports:
      - 6443:8080
      - 8081:8081
