version: '3.4'

services:
  api.mapserv.utah.gov:
    image: ${DOCKER_REGISTRY}apimapservutahgov
    build:
      context: .
      dockerfile: api.mapserv.utah.gov/Dockerfile
  postgres:
    image: postgres:10.4
  redis:
    image: redis:latest
