version: '3'

services:

  api:
    ports:
      - "1337:1337"
    environment:
      - WEBAPI__DATABASE__HOST=db
      - WEBAPI__DATABASE__PORT=5432
      - WEBAPI__DATABASE__DB=webapi
      - WEBAPI__DATABASE__USERNAME=postgres
      - WEBAPI__DATABASE__PASSWORD=what password
      - WEBAPI__ARCGIS__HOST=localhost
      - WEBAPI__ARCGIS__PORT=6080
      - WEBAPI__ARCGIS__GEOMETRY_SERVICE__PATH=arcgis/rest/services/Geometry/GeometryServer
      - ASPNETCORE_URLS=http://+:1337
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - db
      - cache

  developer:
    ports:
      - "1338:1338"
    environment:
      - WEBAPI__DATABASE__HOST=db
      - WEBAPI__DATABASE__PORT=5432
      - WEBAPI__DATABASE__DB=webapi
      - WEBAPI__DATABASE__USERNAME=postgres
      - WEBAPI__DATABASE__PASSWORD=what password
      - WEBAPI__DATABASE__PEPPER=spicy
      - ASPNETCORE_URLS=http://+:1338
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - db

  db:
    environment:
      - POSTGRES_PASSWORD=what password
      - POSTGRES_DB=webapi
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  cache:
    ports:
      - '6379:6379'

volumes:
  pgdata:
    external: true
