version: '3.4'

services:
  webapi-core:
    image: ${DOCKER_REGISTRY}webapi
    build:
      context: .
      dockerfile: api.mapserv.utah.gov/Dockerfile
  postgres:
    image: postgres:10.4
  redis:
    image: redis:latest
