version: '3.6'

services:
  webapi-core:
    links:
      - db
      - cache
    environment:
      - ASPNETCORE_URLS=http://+:1337
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
    ports:
      - "1337:1337"
  db:
    environment:
      - POSTGRES_DB=webapi
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
    external: true
