using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace graphql.schemas
{
    public partial class CensusPlaces2010
    {
        public int Xid { get; set; }
        public string Statefp10 { get; set; }
        public string Placefp10 { get; set; }
        public string Placens10 { get; set; }
        public string Geoid10 { get; set; }
        public string Name10 { get; set; }
        public string Namelsad10 { get; set; }
        public string Lsad10 { get; set; }
        public string Classfp10 { get; set; }
        public string Pcicbsa10 { get; set; }
        public string Pcinecta10 { get; set; }
        public string Mtfcc10 { get; set; }
        public string Funcstat10 { get; set; }
        public decimal? Aland10 { get; set; }
        public decimal? Awater10 { get; set; }
        public string Intptlat10 { get; set; }
        public string Intptlon10 { get; set; }
        public decimal? Tapersons { get; set; }
        public decimal? Ta1race { get; set; }
        public decimal? Tawhitealn { get; set; }
        public decimal? Tablackaln { get; set; }
        public decimal? Taamindaln { get; set; }
        public decimal? Taasianaln { get; set; }
        public decimal? Tanhpoaln { get; set; }
        public decimal? Taotheraln { get; set; }
        public decimal? Ta2race { get; set; }
        public decimal? Tapop2race { get; set; }
        public decimal? Tawhtblack { get; set; }
        public decimal? Tawhaian { get; set; }
        public decimal? Tawhtasian { get; set; }
        public decimal? Tawhnhpo { get; set; }
        public decimal? Tawhtother { get; set; }
        public decimal? Tablaian { get; set; }
        public decimal? Tablkasian { get; set; }
        public decimal? Tablnhpo { get; set; }
        public decimal? Tablkother { get; set; }
        public decimal? Taaianas { get; set; }
        public decimal? Taaiannhp { get; set; }
        public decimal? Taaianor { get; set; }
        public decimal? Taasnhpo { get; set; }
        public decimal? Taasianoth { get; set; }
        public decimal? Tanhpoor { get; set; }
        public decimal? Ta3races { get; set; }
        public decimal? Tawhblain { get; set; }
        public decimal? Tawhblas { get; set; }
        public decimal? Tawhblnhp { get; set; }
        public decimal? Tawhblor { get; set; }
        public decimal? Tawhaians { get; set; }
        public decimal? Tawhaianhp { get; set; }
        public decimal? Tawhaianor { get; set; }
        public decimal? Tawasnhopi { get; set; }
        public decimal? Tawhasor { get; set; }
        public decimal? Tawhnhpoot { get; set; }
        public decimal? Tablaians { get; set; }
        public decimal? Tablaianhp { get; set; }
        public decimal? Tablaianor { get; set; }
        public decimal? Tablasnhop { get; set; }
        public decimal? Tablasor { get; set; }
        public decimal? Tablnhpoor { get; set; }
        public decimal? Taaianashp { get; set; }
        public decimal? Taaianasor { get; set; }
        public decimal? Taaiannhpo { get; set; }
        public decimal? Taasnhpoor { get; set; }
        public decimal? Ta4races { get; set; }
        public decimal? Tawhblaina { get; set; }
        public decimal? Tawhblinhp { get; set; }
        public decimal? Tawhblaino { get; set; }
        public decimal? Tawhblashp { get; set; }
        public decimal? Tawhblasor { get; set; }
        public decimal? Tawhblnhpo { get; set; }
        public decimal? Tawhainshp { get; set; }
        public decimal? Tawhaianso { get; set; }
        public decimal? Tawhainhpo { get; set; }
        public decimal? Tawhasnhpo { get; set; }
        public decimal? Tablainshp { get; set; }
        public decimal? Tablaianso { get; set; }
        public decimal? Tablainhpo { get; set; }
        public decimal? Tablasnhpo { get; set; }
        public decimal? Taaianshpo { get; set; }
        public decimal? Ta5races { get; set; }
        public decimal? Tawhbinshp { get; set; }
        public decimal? Tawhblinso { get; set; }
        public decimal? Tawhbinhpo { get; set; }
        public decimal? Tawhblshpo { get; set; }
        public decimal? Tawhinshpo { get; set; }
        public decimal? Tablinshpo { get; set; }
        public decimal? Ta6races { get; set; }
        public decimal? Twhbinshpo { get; set; }
        public decimal? Thispnhisp { get; set; }
        public decimal? Tahispanic { get; set; }
        public decimal? Tnhispanic { get; set; }
        public decimal? Tn1race { get; set; }
        public decimal? Tnwhaln { get; set; }
        public decimal? Tnblkaln { get; set; }
        public decimal? Tnaianaln { get; set; }
        public decimal? Tnasianaln { get; set; }
        public decimal? Tnnhpoaln { get; set; }
        public decimal? Tnothraln { get; set; }
        public decimal? Tn2mraces { get; set; }
        public decimal? Tn2races { get; set; }
        public decimal? Tnwhbl { get; set; }
        public decimal? Tnwhaian { get; set; }
        public decimal? Tnwhtasian { get; set; }
        public decimal? Tnwhnhpopi { get; set; }
        public decimal? Tnwhor { get; set; }
        public decimal? Tnblaian { get; set; }
        public decimal? Tnblasian { get; set; }
        public decimal? Tnblnhpopi { get; set; }
        public decimal? Tnblor { get; set; }
        public decimal? Tnaianas { get; set; }
        public decimal? Tnaiannhpi { get; set; }
        public decimal? Tnaianor { get; set; }
        public decimal? Tnasnhpopi { get; set; }
        public decimal? Tnasor { get; set; }
        public decimal? Tnnhopioor { get; set; }
        public decimal? Tn3races { get; set; }
        public decimal? Tnwhblaian { get; set; }
        public decimal? Tnwhblas { get; set; }
        public decimal? Tnwhblnhpi { get; set; }
        public decimal? Tnwhblor { get; set; }
        public decimal? Tnwhaianas { get; set; }
        public decimal? Tnwhaianhp { get; set; }
        public decimal? Tnwhaianor { get; set; }
        public decimal? Tnwhasnhpi { get; set; }
        public decimal? Tnwhasor { get; set; }
        public decimal? Tnwhnhpoor { get; set; }
        public decimal? Tnblaianas { get; set; }
        public decimal? Tnblaianhp { get; set; }
        public decimal? Tnblaianor { get; set; }
        public decimal? Tnblasnhpi { get; set; }
        public decimal? Tnblasor { get; set; }
        public decimal? Tnblnhpoor { get; set; }
        public decimal? Tnaianashp { get; set; }
        public decimal? Tnaianasor { get; set; }
        public decimal? Tnaiannhpo { get; set; }
        public decimal? Tnasnhpoor { get; set; }
        public decimal? Tn4races { get; set; }
        public decimal? Tnwhblains { get; set; }
        public decimal? Tnwhblinhp { get; set; }
        public decimal? Tnwhblaino { get; set; }
        public decimal? Tnwhblashp { get; set; }
        public decimal? Tnwhblasor { get; set; }
        public decimal? Tnwhblnhpo { get; set; }
        public decimal? Tnwhainshp { get; set; }
        public decimal? Tnwhaianso { get; set; }
        public decimal? Tnwhainhpo { get; set; }
        public decimal? Tnwhasnhpo { get; set; }
        public decimal? Tnblainshp { get; set; }
        public decimal? Tnblaianso { get; set; }
        public decimal? Tnblainhpo { get; set; }
        public decimal? Tnblasnhpo { get; set; }
        public decimal? Tnaianshpo { get; set; }
        public decimal? Tn5races { get; set; }
        public decimal? Tnwhbinshp { get; set; }
        public decimal? Tnwhblinso { get; set; }
        public decimal? Tnwhbinhpo { get; set; }
        public decimal? Tnwhblshpo { get; set; }
        public decimal? Tnwhinshpo { get; set; }
        public decimal? Tnblinshpo { get; set; }
        public decimal? Tn6races { get; set; }
        public decimal? Tnwbinshpo { get; set; }
        public decimal? Vapersons { get; set; }
        public decimal? Va1race { get; set; }
        public decimal? Vawhitealn { get; set; }
        public decimal? Vablackaln { get; set; }
        public decimal? Vaaianaln { get; set; }
        public decimal? Vaasianaln { get; set; }
        public decimal? Vanhpoaln { get; set; }
        public decimal? Vaotheraln { get; set; }
        public decimal? Va2mraces { get; set; }
        public decimal? Va2races { get; set; }
        public decimal? Vawhbl { get; set; }
        public decimal? Vawhaian { get; set; }
        public decimal? Vawhas { get; set; }
        public decimal? Vawhnhpo { get; set; }
        public decimal? Vawhor { get; set; }
        public decimal? Vablaian { get; set; }
        public decimal? Vablasian { get; set; }
        public decimal? Vablnhopi { get; set; }
        public decimal? Vablor { get; set; }
        public decimal? Vaaianas { get; set; }
        public decimal? Vaaiannhpi { get; set; }
        public decimal? Vaaianor { get; set; }
        public decimal? Vaasnhopi { get; set; }
        public decimal? Vaasor { get; set; }
        public decimal? Vanhpoor { get; set; }
        public decimal? Va3races { get; set; }
        public decimal? Vawhblaian { get; set; }
        public decimal? Vawhblas { get; set; }
        public decimal? Vawhblnhpi { get; set; }
        public decimal? Vawhblor { get; set; }
        public decimal? Vawhaianas { get; set; }
        public decimal? Vawhaianhp { get; set; }
        public decimal? Vawhaianor { get; set; }
        public decimal? Vawhasnhpi { get; set; }
        public decimal? Vawhasor { get; set; }
        public decimal? Vawhnhpiot { get; set; }
        public decimal? Vablaianas { get; set; }
        public decimal? Vablaianhp { get; set; }
        public decimal? Vablaianor { get; set; }
        public decimal? Vablasnhpi { get; set; }
        public decimal? Vablasor { get; set; }
        public decimal? Vablnhpiot { get; set; }
        public decimal? Vaaianashp { get; set; }
        public decimal? Vaaianasor { get; set; }
        public decimal? Vaaiannhpo { get; set; }
        public decimal? Vaasnhpoor { get; set; }
        public decimal? Va4races { get; set; }
        public decimal? Vawhblains { get; set; }
        public decimal? Vawhblinhp { get; set; }
        public decimal? Vawhblaino { get; set; }
        public decimal? Vawhblashp { get; set; }
        public decimal? Vawhblasor { get; set; }
        public decimal? Vawhblnhpo { get; set; }
        public decimal? Vawhainshp { get; set; }
        public decimal? Vawhaianso { get; set; }
        public decimal? Vawhainhpo { get; set; }
        public decimal? Vawhasnhpo { get; set; }
        public decimal? Vablainshp { get; set; }
        public decimal? Vablaianso { get; set; }
        public decimal? Vablainhpo { get; set; }
        public decimal? Vablasnhpo { get; set; }
        public decimal? Vaaianshpo { get; set; }
        public decimal? Va5races { get; set; }
        public decimal? Vawhbinshp { get; set; }
        public decimal? Vawhblinso { get; set; }
        public decimal? Vawhbinhpo { get; set; }
        public decimal? Vawhblshpo { get; set; }
        public decimal? Vawhinshpo { get; set; }
        public decimal? Vablinshpo { get; set; }
        public decimal? Va6races { get; set; }
        public decimal? Vawbinshpo { get; set; }
        public decimal? Vahisnhisp { get; set; }
        public decimal? Vahispanic { get; set; }
        public decimal? Vanhispanc { get; set; }
        public decimal? Van1race { get; set; }
        public decimal? Vanwhtaln { get; set; }
        public decimal? Vanblkaln { get; set; }
        public decimal? Vanaianaln { get; set; }
        public decimal? Vanasanaln { get; set; }
        public decimal? Vannhpoaln { get; set; }
        public decimal? Vanoraln { get; set; }
        public decimal? Vanm2races { get; set; }
        public decimal? Van2races { get; set; }
        public decimal? Vanwhbl { get; set; }
        public decimal? Vanwhaian { get; set; }
        public decimal? Vanwhas { get; set; }
        public decimal? Vanwhnhopi { get; set; }
        public decimal? Vanwhor { get; set; }
        public decimal? Vanblaian { get; set; }
        public decimal? Vanblas { get; set; }
        public decimal? Vanblnhopi { get; set; }
        public decimal? Vanblor { get; set; }
        public decimal? Vanaianas { get; set; }
        public decimal? Vanaiannhp { get; set; }
        public decimal? Vanaianor { get; set; }
        public decimal? Vanasnhopi { get; set; }
        public decimal? Vanasor { get; set; }
        public decimal? Vannhopior { get; set; }
        public decimal? Van3races { get; set; }
        public decimal? Vanwhblain { get; set; }
        public decimal? Vanwhblas { get; set; }
        public decimal? Vanwhblnhp { get; set; }
        public decimal? Vanwhblor { get; set; }
        public decimal? Vanwhaians { get; set; }
        public decimal? Vanwhainhp { get; set; }
        public decimal? Vanwhaiano { get; set; }
        public decimal? Vanwhasnhp { get; set; }
        public decimal? Vanwhasor { get; set; }
        public decimal? Vanwhnhopo { get; set; }
        public decimal? Vanblaians { get; set; }
        public decimal? Vanblainhp { get; set; }
        public decimal? Vanblaiano { get; set; }
        public decimal? Vanblasnhp { get; set; }
        public decimal? Vanblasor { get; set; }
        public decimal? Vanblnhopo { get; set; }
        public decimal? Vanaianshp { get; set; }
        public decimal? Vanaianaso { get; set; }
        public decimal? Vanaianhpo { get; set; }
        public decimal? Vanasnhpoo { get; set; }
        public decimal? Van4races { get; set; }
        public decimal? Vanwhblins { get; set; }
        public decimal? Vanwhbinhp { get; set; }
        public decimal? Vanwhblino { get; set; }
        public decimal? Vanwhblshp { get; set; }
        public decimal? Vanwhblaso { get; set; }
        public decimal? Vanwhblhpo { get; set; }
        public decimal? Vanwhinshp { get; set; }
        public decimal? Vanwhainso { get; set; }
        public decimal? Vanwhinhpo { get; set; }
        public decimal? Vanwhashpo { get; set; }
        public decimal? Vanblinshp { get; set; }
        public decimal? Vanblainso { get; set; }
        public decimal? Vanblinhpo { get; set; }
        public decimal? Vanblashpo { get; set; }
        public decimal? Vanainshpo { get; set; }
        public decimal? Van5races { get; set; }
        public decimal? Vanwbinshp { get; set; }
        public decimal? Vanwhbinso { get; set; }
        public decimal? Vanwbinhpo { get; set; }
        public decimal? Vanwhbshpo { get; set; }
        public decimal? Vanwinshpo { get; set; }
        public decimal? Vanbinshpo { get; set; }
        public decimal? Van6races { get; set; }
        public decimal? Vnwbinshpo { get; set; }
        public decimal? Tahousing { get; set; }
        public decimal? Tahoccupid { get; set; }
        public decimal? Tahvacant { get; set; }
        public MultiPolygon Shape { get; set; }
    }
}
