using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace graphql.schemas
{
    public partial class CensusBlocks2010
    {
        public int Xid { get; set; }
        public string Statefp10 { get; set; }
        public string Countyfp10 { get; set; }
        public string Tractce10 { get; set; }
        public string Blockce10 { get; set; }
        public string Geoid10 { get; set; }
        public string Name10 { get; set; }
        public string Ur10 { get; set; }
        public string Uace10 { get; set; }
        public string Funcstat10 { get; set; }
        public decimal? Aland10 { get; set; }
        public decimal? Awater10 { get; set; }
        public string Intptlat10 { get; set; }
        public string Intptlon10 { get; set; }
        public string Fileid { get; set; }
        public string Stusab { get; set; }
        public string Sumlev { get; set; }
        public string Geocomp { get; set; }
        public string Chariter { get; set; }
        public string Cifsn { get; set; }
        public string Logrecno { get; set; }
        public string Region { get; set; }
        public string Division { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string Countycc { get; set; }
        public string Countysc { get; set; }
        public string Cousub { get; set; }
        public string Cousubcc { get; set; }
        public string Cousubsc { get; set; }
        public string Place { get; set; }
        public string Placecc { get; set; }
        public string Placesc { get; set; }
        public string Tract { get; set; }
        public string Blkgrp { get; set; }
        public string Block { get; set; }
        public string Iuc { get; set; }
        public string Concit { get; set; }
        public string Concitcc { get; set; }
        public string Concitsc { get; set; }
        public string Aianhh { get; set; }
        public string Aianhhfp { get; set; }
        public string Aianhhcc { get; set; }
        public string Aihhtli { get; set; }
        public string Aitsce { get; set; }
        public string Aits { get; set; }
        public string Aitscc { get; set; }
        public string Ttract { get; set; }
        public string Tblkgrp { get; set; }
        public string Cbsa { get; set; }
        public string Cbsasc { get; set; }
        public string Csa { get; set; }
        public string Cbsapci { get; set; }
        public string Ua { get; set; }
        public string Uasc { get; set; }
        public string Uatype { get; set; }
        public string Ur { get; set; }
        public string Cd { get; set; }
        public string Sldu { get; set; }
        public string Sldl { get; set; }
        public string Vtd { get; set; }
        public string Vtdi { get; set; }
        public string Reserve2 { get; set; }
        public string Zcta5 { get; set; }
        public string Submcd { get; set; }
        public string Submcdcc { get; set; }
        public string Sdelm { get; set; }
        public string Sdsec { get; set; }
        public string Sduni { get; set; }
        public string Arealand { get; set; }
        public string Areawatr { get; set; }
        public string Name { get; set; }
        public string Funcstat { get; set; }
        public string Gcuni { get; set; }
        public decimal? Pop100 { get; set; }
        public decimal? Hu100 { get; set; }
        public string Intptlat { get; set; }
        public string Intptlon { get; set; }
        public string Lsadc { get; set; }
        public string Partflag { get; set; }
        public string Reserve3 { get; set; }
        public string Uga { get; set; }
        public string Statens { get; set; }
        public string Countyns { get; set; }
        public string Cousubns { get; set; }
        public string Placens { get; set; }
        public string Concitns { get; set; }
        public string Aianhhns { get; set; }
        public string Aitsns { get; set; }
        public string Anrcns { get; set; }
        public string Submcdns { get; set; }
        public string Aianhhsc { get; set; }
        public string Csasc { get; set; }
        public string Cnectasc { get; set; }
        public string Memi { get; set; }
        public string Nmemi { get; set; }
        public string Puma { get; set; }
        public string Reserved { get; set; }
        public decimal? P0020001 { get; set; }
        public decimal? P0020002 { get; set; }
        public decimal? P0020003 { get; set; }
        public decimal? P0020004 { get; set; }
        public decimal? P0020005 { get; set; }
        public decimal? P0020006 { get; set; }
        public decimal? P0020007 { get; set; }
        public decimal? P0020008 { get; set; }
        public decimal? P0020009 { get; set; }
        public decimal? P0020010 { get; set; }
        public string Mtfcc { get; set; }
        public decimal? P0010011 { get; set; }
        public decimal? P0010012 { get; set; }
        public decimal? P0010013 { get; set; }
        public decimal? P0010014 { get; set; }
        public decimal? Sqmiles { get; set; }
        public string Urbanrural { get; set; }
        public MultiPolygon Shape { get; set; }
    }
}
