@hostname = localhost
@port = 1337
@host = {{hostname}}:{{port}}
@apiKey = apikey=agrc-dev
@milepost = http://{{host}}/api/v1/geocode/milepost/15/301.009?{{apiKey}}

GET {{milepost}}
###
GET {{milepost}}&side=decreasing
###
GET {{milepost}}&callback=jsonp
###
GET {{milepost}}&format=geojson
###
GET {{milepost}}&format=esrijson
###
GET {{milepost}}&spatialReference=4326
###
GET http://{{host}}/api/v1/geocode/milepost/0015PC30554/1.1?{{apiKey}}&fullRoute=true
###
// Validation Error
GET http://{{host}}/api/v1/geocode/milepost/%20/%20?{{apiKey}}
###
###
// 404
GET http://{{host}}/api/v1/geocode/milepost/19/20?{{apiKey}}
###
