@hostname = localhost
@port = 1337
@host = {{hostname}}:{{port}}
@apiKey = apikey=agrc-dev
@reverse = http://{{host}}/api/v1/geocode/reverse/425608/4513499?{{apiKey}}

GET {{reverse}}
###
GET {{reverse}}&distance=1
###
GET {{reverse}}&format=esrijson
###
GET {{reverse}}&callback=jsonp
###
GET http://{{host}}/api/v1/geocode/reverse/-111.7118/40.30984?{{apiKey}}&spatialReference=4326
###
// Validation Error
GET http://{{host}}/api/v1/geocode/reverse/%20/%20?{{apiKey}}
###
