@hostname = localhost
@port = 1337
@host = {{hostname}}:{{port}}
@apiKey = apikey=agrc-dev
@single = http://{{host}}/api/v1/geocode/326 east south temple/slc?{{apiKey}}

GET {{single}}
###
GET {{single}}&suggest=2
###
GET {{single}}&format=geojson
###
GET {{single}}&format=esrijson
###
GET {{single}}&callback=jsonp
###
GET {{single}}&acceptScore=92&suggest=2
###
GET {{single}}&acceptScore=92&scoreDifference=true
###
GET {{single}}&acceptScore=92&locators=roadCenterlines
###
GET {{single}}&acceptScore=92&locators=addressPoints&suggest=2
###
// Validation Error
GET http://{{host}}/api/v1/geocode/%20/%20?{{apiKey}}
###
