apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config.yaml
- database.yaml
- certificates.yaml
- api.yaml
- ingress.yaml
- explorer.yaml

configMapGenerator:
  - name: api-app-settings
    files:
    - config-files/appsettings.json

secretGenerator:
  - name: logging-service-account
    files:
      - secrets/ut-dts-agrc-web-api-dv-log-writer.json
