name: Test API

on:
  push:
    branches-ignore:
    - development
    paths-ignore:
    - '*.md'
  pull_request:
    paths:
    - 'src/api/**'
    - 'libs/**'
    - '.github/workflows/dotnetcore.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Cache NuGet Packages
      uses: actions/cache@v2
      with:
        # nuget cache files are stored in `~/.nuget/packages` on Linux/macOS
        path: ~/.nuget/packages
        key: ${{ runner.OS }}-nuget-${{ hashFiles('**/Packages.targets') }}
        restore-keys: |
          ${{ runner.OS }}-nuget-
          ${{ runner.OS }}

    - name: Run Tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../../coverage.xml /p:Configuration=Release api.mapserv.utah.gov.sln --verbosity q --nologo

    - name: Report coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
