name: Push Events

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  release-main:
    name: Release PR (main)
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: 🪙 Convert token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          owner: ${{ github.repository_owner }}
          repositories: "api.mapserv.utah.gov"
          app-id: ${{ secrets.UGRC_RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.UGRC_RELEASE_BOT_APP_KEY }}

      - name: ⬇️ Set up code
        uses: actions/checkout@v6
        with:
          show-progress: false
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: 🚀 Create release
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}

  release-dev:
    name: Pre-release PR (dev)
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: 🪙 Convert token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          owner: ${{ github.repository_owner }}
          repositories: "api.mapserv.utah.gov"
          app-id: ${{ secrets.UGRC_RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.UGRC_RELEASE_BOT_APP_KEY }}

      - name: ⬇️ Set up code
        uses: actions/checkout@v6
        with:
          show-progress: false
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: 🚀 Create pre-release
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          target-branch: dev
          config-file: release-please-config.dev.json
          manifest-file: .release-please-manifest.dev.json
